"""portfolio and holdings tabl

Revision ID: 272bf5875fb9
Revises: 443ed5f2dd85
Create Date: 2020-09-29 11:17:47.766038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272bf5875fb9'
down_revision = '443ed5f2dd85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=6), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holding')
    op.drop_table('portfolio')
    # ### end Alembic commands ###
